# Generated by Django 3.2 on 2021-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='importance',
            field=models.FloatField(default=0),
        ),
    ]
