# Generated by Django 3.2 on 2021-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0003_logs_reporter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_news',
            field=models.BooleanField(default=False),
        ),
    ]
