# Generated by Django 3.2 on 2021-04-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0004_news_main_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'My Book', 'verbose_name_plural': 'My Books'},
        ),
    ]
