settings = dict(title="Интерактивная игра по запоминанию китайских иероглифов",
                size='900x600',
                begin_game_label='Начать игру',
                begin_game_button="Нажмите, чтобы начать новую игру",
                help_button='Помощь',
                help_label="Нажмите, чтобы прочитать инструкцию по приложению",
                exit_button='Выход',
                exit_label="Нажмите, чтобы выйти из приложения",
                main_menu='Главное меню',
                font_small=("Helvetica", 16),
                font_chars=("Helvetica", "130"),
                font_medium=("Helvetica", 25),
                font_symbols=("Helvetica", "16"),
                font_progress=("Helvetica", "80"),
                choose_lesson='Выберите урок',
                choose_lesson_button='Выберать урок',
                choose_your_lesson='Выберите желаемый урок',
                font_info=("Calibri", 14),
                hide_button="Увидеть/скрыть\nподсказку",
                seen_all='Вы просмотрели все иероглифы\nв данном уроке',
                next_hieroglyph='Следующий иероглиф',
                prev_hieroglyph='Предыдущий иероглиф'
                )
